// Comprehensive mock data simulating Meta Graph API responses
import { 
  SocialAccount, 
  Post, 
  Comment, 
  AudienceDemographics,
  AudienceGrowth,
  EngagementAnalytics,
  SentimentAnalytics,
  BestPostingTime,
  AIInsight,
  TrendingTopic,
} from './types';

// Helper to generate dates
const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

// Mock Social Accounts
export const mockAccounts: SocialAccount[] = [
  {
    id: 'ig-001',
    platform: 'instagram',
    username: 'mybrand',
    name: 'My Brand Official',
    profilePictureUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=MB',
    followersCount: 48500,
    followingCount: 892,
    postsCount: 342,
    biography: 'Official account | Innovating since 2020',
    website: 'https://mybrand.com',
    isConnected: true,
  },
  {
    id: 'tw-001',
    platform: 'twitter',
    username: 'mybrand',
    name: 'My Brand',
    profilePictureUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=MB',
    followersCount: 23400,
    followingCount: 1205,
    postsCount: 1892,
    biography: 'Building the future | Customer-first',
    isConnected: true,
  },
  {
    id: 'fb-001',
    platform: 'facebook',
    username: 'mybrand',
    name: 'My Brand',
    profilePictureUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=MB',
    followersCount: 67200,
    followingCount: 0,
    postsCount: 567,
    isConnected: true,
  },
  {
    id: 'li-001',
    platform: 'linkedin',
    username: 'mybrand',
    name: 'My Brand Inc.',
    profilePictureUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=MB',
    followersCount: 15800,
    followingCount: 234,
    postsCount: 189,
    isConnected: true,
  },
];

// Mock Posts with realistic engagement patterns
export const mockPosts: Post[] = [
  {
    id: 'post-001',
    platform: 'instagram',
    accountId: 'ig-001',
    externalId: '17895695668004550',
    type: 'carousel',
    content: '🚀 Exciting news! We just launched our new product line. Check out the link in bio to explore! #NewLaunch #Innovation #2024',
    mediaUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400',
    permalink: 'https://instagram.com/p/abc123',
    publishedAt: daysAgo(1),
    metrics: {
      likes: 4520,
      comments: 234,
      shares: 89,
      saves: 312,
      reach: 45600,
      impressions: 67800,
      engagementRate: 8.2,
    },
    hashtags: ['#NewLaunch', '#Innovation', '#2024'],
    mentions: [],
  },
  {
    id: 'post-002',
    platform: 'instagram',
    accountId: 'ig-001',
    type: 'reel',
    content: '📸 Behind the scenes at our office! Meet the amazing team making it all happen. #TeamLife #BehindTheScenes',
    mediaUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800',
    publishedAt: daysAgo(2),
    metrics: {
      likes: 6780,
      comments: 456,
      shares: 234,
      saves: 567,
      reach: 89000,
      impressions: 134000,
      engagementRate: 9.1,
      videoViews: 45600,
    },
    hashtags: ['#TeamLife', '#BehindTheScenes'],
    mentions: [],
  },
  {
    id: 'post-003',
    platform: 'twitter',
    accountId: 'tw-001',
    type: 'text',
    content: 'We are thrilled to announce our partnership with @TechCorp! Together, we will revolutionize the industry. Stay tuned for more updates! 🎉',
    publishedAt: daysAgo(3),
    metrics: {
      likes: 1890,
      comments: 167,
      shares: 456,
      saves: 0,
      reach: 34500,
      impressions: 78000,
      engagementRate: 6.5,
    },
    hashtags: [],
    mentions: ['@TechCorp'],
  },
  {
    id: 'post-004',
    platform: 'instagram',
    accountId: 'ig-001',
    type: 'image',
    content: 'Customer spotlight ✨ Thank you @happycustomer for sharing your story with us! #CustomerLove #Testimonial',
    mediaUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800',
    publishedAt: daysAgo(4),
    metrics: {
      likes: 3450,
      comments: 189,
      shares: 67,
      saves: 234,
      reach: 38000,
      impressions: 52000,
      engagementRate: 7.8,
    },
    hashtags: ['#CustomerLove', '#Testimonial'],
    mentions: ['@happycustomer'],
  },
  {
    id: 'post-005',
    platform: 'facebook',
    accountId: 'fb-001',
    type: 'video',
    content: 'Watch our CEO talk about the future of technology and where we are headed in 2024! Full video on our YouTube channel.',
    mediaUrl: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=800',
    publishedAt: daysAgo(5),
    metrics: {
      likes: 2340,
      comments: 312,
      shares: 178,
      saves: 0,
      reach: 56000,
      impressions: 89000,
      engagementRate: 5.2,
      videoViews: 23400,
    },
    hashtags: [],
    mentions: [],
  },
  {
    id: 'post-006',
    platform: 'linkedin',
    accountId: 'li-001',
    type: 'text',
    content: 'We are hiring! Join our growing team of innovators. Check out the open positions: Software Engineers, Product Managers, and UX Designers. #Hiring #TechJobs #Careers',
    publishedAt: daysAgo(6),
    metrics: {
      likes: 890,
      comments: 134,
      shares: 267,
      saves: 0,
      reach: 28000,
      impressions: 45000,
      engagementRate: 4.6,
    },
    hashtags: ['#Hiring', '#TechJobs', '#Careers'],
    mentions: [],
  },
  {
    id: 'post-007',
    platform: 'instagram',
    accountId: 'ig-001',
    type: 'story',
    content: 'Quick poll: What feature would you like to see next? A) Dark mode B) Mobile app C) Integrations',
    publishedAt: daysAgo(7),
    metrics: {
      likes: 0,
      comments: 0,
      shares: 45,
      saves: 0,
      reach: 12000,
      impressions: 15600,
      engagementRate: 12.3,
    },
    hashtags: [],
    mentions: [],
  },
  {
    id: 'post-008',
    platform: 'twitter',
    accountId: 'tw-001',
    type: 'text',
    content: 'Scheduled maintenance tonight from 11 PM - 2 AM EST. Services may be briefly unavailable. We apologize for any inconvenience.',
    publishedAt: daysAgo(8),
    metrics: {
      likes: 234,
      comments: 89,
      shares: 156,
      saves: 0,
      reach: 18000,
      impressions: 28000,
      engagementRate: 2.6,
    },
    hashtags: [],
    mentions: [],
  },
];

// Mock Comments with varied sentiments
export const mockComments: Comment[] = [
  {
    id: 'comment-001',
    postId: 'post-001',
    authorName: 'Sarah Johnson',
    authorUsername: 'sarahj',
    content: 'This is amazing! Cannot wait to try the new products. You guys always deliver quality! 🔥',
    createdAt: daysAgo(1),
    likes: 45,
    sentiment: 'positive',
    sentimentScore: 0.92,
    isReply: false,
  },
  {
    id: 'comment-002',
    postId: 'post-001',
    authorName: 'Mike Chen',
    authorUsername: 'mikechen',
    content: 'When will this be available in Europe? Really hoping for international shipping!',
    createdAt: daysAgo(1),
    likes: 23,
    sentiment: 'neutral',
    sentimentScore: 0.55,
    isReply: false,
  },
  {
    id: 'comment-003',
    postId: 'post-001',
    authorName: 'Emma Williams',
    authorUsername: 'emmaw',
    content: 'The pricing seems a bit high compared to competitors. Any discounts planned?',
    createdAt: daysAgo(1),
    likes: 12,
    sentiment: 'negative',
    sentimentScore: 0.35,
    isReply: false,
  },
  {
    id: 'comment-004',
    postId: 'post-002',
    authorName: 'Alex Rivera',
    authorUsername: 'alexr',
    content: 'Love seeing the team behind the brand! You all seem so passionate about your work.',
    createdAt: daysAgo(2),
    likes: 67,
    sentiment: 'positive',
    sentimentScore: 0.88,
    isReply: false,
  },
  {
    id: 'comment-005',
    postId: 'post-002',
    authorName: 'Jordan Lee',
    authorUsername: 'jordanl',
    content: 'Your company culture looks incredible! Are you hiring remote?',
    createdAt: daysAgo(2),
    likes: 34,
    sentiment: 'positive',
    sentimentScore: 0.82,
    isReply: false,
  },
  {
    id: 'comment-006',
    postId: 'post-003',
    authorName: 'Chris Taylor',
    authorUsername: 'christ',
    content: 'This partnership is a game changer! Excited to see what comes next.',
    createdAt: daysAgo(3),
    likes: 89,
    sentiment: 'positive',
    sentimentScore: 0.94,
    isReply: false,
  },
  {
    id: 'comment-007',
    postId: 'post-004',
    authorName: 'Happy Customer',
    authorUsername: 'happycustomer',
    content: 'Thank you so much for featuring me! Your product changed my workflow completely.',
    createdAt: daysAgo(4),
    likes: 156,
    sentiment: 'positive',
    sentimentScore: 0.96,
    isReply: false,
  },
  {
    id: 'comment-008',
    postId: 'post-008',
    authorName: 'Frustrated User',
    authorUsername: 'frustratedd',
    content: 'Another maintenance? This is the third time this month. Please improve your infrastructure.',
    createdAt: daysAgo(8),
    likes: 28,
    sentiment: 'negative',
    sentimentScore: 0.18,
    isReply: false,
  },
  {
    id: 'comment-009',
    postId: 'post-008',
    authorName: 'Support Fan',
    authorUsername: 'supportfan',
    content: 'Thanks for the heads up! Appreciate the transparency.',
    createdAt: daysAgo(8),
    likes: 15,
    sentiment: 'positive',
    sentimentScore: 0.75,
    isReply: false,
  },
];

// Mock Audience Demographics
export const mockDemographics: AudienceDemographics = {
  accountId: 'ig-001',
  platform: 'instagram',
  totalFollowers: 48500,
  ageGenderBreakdown: [
    { ageRange: '13-17', gender: 'male', percentage: 3, count: 1455 },
    { ageRange: '13-17', gender: 'female', percentage: 4, count: 1940 },
    { ageRange: '18-24', gender: 'male', percentage: 14, count: 6790 },
    { ageRange: '18-24', gender: 'female', percentage: 18, count: 8730 },
    { ageRange: '25-34', gender: 'male', percentage: 16, count: 7760 },
    { ageRange: '25-34', gender: 'female', percentage: 19, count: 9215 },
    { ageRange: '35-44', gender: 'male', percentage: 9, count: 4365 },
    { ageRange: '35-44', gender: 'female', percentage: 8, count: 3880 },
    { ageRange: '45-54', gender: 'male', percentage: 4, count: 1940 },
    { ageRange: '45-54', gender: 'female', percentage: 3, count: 1455 },
    { ageRange: '55+', gender: 'male', percentage: 1, count: 485 },
    { ageRange: '55+', gender: 'female', percentage: 1, count: 485 },
  ],
  topCities: [
    { name: 'New York, NY', percentage: 12, count: 5820 },
    { name: 'Los Angeles, CA', percentage: 9, count: 4365 },
    { name: 'London, UK', percentage: 7, count: 3395 },
    { name: 'Chicago, IL', percentage: 5, count: 2425 },
    { name: 'Toronto, CA', percentage: 4, count: 1940 },
    { name: 'Sydney, AU', percentage: 3, count: 1455 },
  ],
  topCountries: [
    { name: 'United States', percentage: 45, count: 21825 },
    { name: 'United Kingdom', percentage: 15, count: 7275 },
    { name: 'Canada', percentage: 10, count: 4850 },
    { name: 'Australia', percentage: 8, count: 3880 },
    { name: 'Germany', percentage: 6, count: 2910 },
    { name: 'France', percentage: 4, count: 1940 },
    { name: 'Other', percentage: 12, count: 5820 },
  ],
};

// Mock Audience Growth (last 30 days)
export const mockAudienceGrowth: AudienceGrowth[] = Array.from({ length: 30 }, (_, i) => {
  const baseFollowers = 45000 + i * 120;
  const newFollowers = Math.floor(Math.random() * 200) + 100;
  const lostFollowers = Math.floor(Math.random() * 50) + 20;
  return {
    date: daysAgo(29 - i),
    followersCount: baseFollowers + newFollowers - lostFollowers,
    followingCount: 890 + Math.floor(i / 3),
    newFollowers,
    lostFollowers,
    netChange: newFollowers - lostFollowers,
  };
});

// Mock Engagement Analytics (last 30 days)
export const mockEngagementAnalytics: EngagementAnalytics[] = Array.from({ length: 30 }, (_, i) => ({
  date: daysAgo(29 - i),
  likes: Math.floor(Math.random() * 3000) + 1500,
  comments: Math.floor(Math.random() * 300) + 100,
  shares: Math.floor(Math.random() * 150) + 50,
  saves: Math.floor(Math.random() * 200) + 80,
  reach: Math.floor(Math.random() * 50000) + 25000,
  impressions: Math.floor(Math.random() * 80000) + 40000,
  profileViews: Math.floor(Math.random() * 1000) + 300,
  websiteClicks: Math.floor(Math.random() * 200) + 50,
}));

// Mock Sentiment Analytics (last 14 days)
export const mockSentimentAnalytics: SentimentAnalytics[] = Array.from({ length: 14 }, (_, i) => {
  const positive = Math.floor(Math.random() * 20) + 60;
  const negative = Math.floor(Math.random() * 15) + 5;
  const neutral = 100 - positive - negative;
  return {
    date: daysAgo(13 - i),
    positive,
    negative,
    neutral,
    averageScore: (positive * 1 + neutral * 0.5 + negative * 0) / 100,
    totalComments: Math.floor(Math.random() * 200) + 100,
  };
});

// Mock Best Posting Times
export const mockBestPostingTimes: BestPostingTime[] = [
  { dayOfWeek: 0, hourOfDay: 10, engagementScore: 7.2, sampleSize: 45 },
  { dayOfWeek: 0, hourOfDay: 14, engagementScore: 8.5, sampleSize: 52 },
  { dayOfWeek: 0, hourOfDay: 20, engagementScore: 7.8, sampleSize: 48 },
  { dayOfWeek: 1, hourOfDay: 9, engagementScore: 6.5, sampleSize: 38 },
  { dayOfWeek: 1, hourOfDay: 12, engagementScore: 8.2, sampleSize: 67 },
  { dayOfWeek: 1, hourOfDay: 18, engagementScore: 9.1, sampleSize: 72 },
  { dayOfWeek: 2, hourOfDay: 9, engagementScore: 6.8, sampleSize: 42 },
  { dayOfWeek: 2, hourOfDay: 12, engagementScore: 8.8, sampleSize: 71 },
  { dayOfWeek: 2, hourOfDay: 18, engagementScore: 9.4, sampleSize: 78 },
  { dayOfWeek: 3, hourOfDay: 9, engagementScore: 6.3, sampleSize: 39 },
  { dayOfWeek: 3, hourOfDay: 12, engagementScore: 7.9, sampleSize: 58 },
  { dayOfWeek: 3, hourOfDay: 18, engagementScore: 8.7, sampleSize: 65 },
  { dayOfWeek: 4, hourOfDay: 9, engagementScore: 5.8, sampleSize: 34 },
  { dayOfWeek: 4, hourOfDay: 12, engagementScore: 7.5, sampleSize: 51 },
  { dayOfWeek: 4, hourOfDay: 18, engagementScore: 8.1, sampleSize: 59 },
  { dayOfWeek: 5, hourOfDay: 10, engagementScore: 8.9, sampleSize: 68 },
  { dayOfWeek: 5, hourOfDay: 14, engagementScore: 9.3, sampleSize: 75 },
  { dayOfWeek: 5, hourOfDay: 20, engagementScore: 8.6, sampleSize: 62 },
  { dayOfWeek: 6, hourOfDay: 10, engagementScore: 9.0, sampleSize: 70 },
  { dayOfWeek: 6, hourOfDay: 14, engagementScore: 9.5, sampleSize: 82 },
  { dayOfWeek: 6, hourOfDay: 20, engagementScore: 8.2, sampleSize: 58 },
];

// Mock AI Insights
export const mockAIInsights: AIInsight[] = [
  {
    id: 'insight-001',
    type: 'trend',
    priority: 'high',
    title: 'Video Content Outperforming Images',
    description: 'Your Reels and video posts are generating 67% more engagement than static images. Consider increasing video content frequency.',
    metric: '+67%',
    platform: 'instagram',
    actionable: true,
    createdAt: daysAgo(0),
    isRead: false,
  },
  {
    id: 'insight-002',
    type: 'tip',
    priority: 'medium',
    title: 'Optimal Posting Window',
    description: 'Your audience is most active between 6-8 PM on weekdays. Posts during this window receive 45% higher reach.',
    metric: '6-8 PM',
    actionable: true,
    createdAt: daysAgo(1),
    isRead: false,
  },
  {
    id: 'insight-003',
    type: 'alert',
    priority: 'high',
    title: 'Negative Sentiment Spike',
    description: 'Comments about pricing have 40% negative sentiment. Consider addressing pricing concerns in your next communication.',
    metric: '-40%',
    actionable: true,
    createdAt: daysAgo(2),
    isRead: true,
  },
  {
    id: 'insight-004',
    type: 'opportunity',
    priority: 'medium',
    title: 'Trending Hashtag Opportunity',
    description: '#Sustainability is trending in your industry (+120% mentions). Creating content around this topic could boost visibility.',
    metric: '+120%',
    actionable: true,
    createdAt: daysAgo(3),
    isRead: true,
  },
  {
    id: 'insight-005',
    type: 'trend',
    priority: 'low',
    title: 'Audience Growth Acceleration',
    description: 'Your follower growth rate increased by 23% this month compared to last month. Keep up the great content!',
    metric: '+23%',
    actionable: false,
    createdAt: daysAgo(4),
    isRead: true,
  },
];

// Mock Trending Topics
export const mockTrendingTopics: TrendingTopic[] = [
  {
    topic: 'Innovation',
    hashtag: '#Innovation',
    mentions: 1250,
    growth: 45,
    sentiment: 'positive',
    relatedPosts: ['post-001', 'post-003'],
  },
  {
    topic: 'Sustainability',
    hashtag: '#Sustainability',
    mentions: 980,
    growth: 120,
    sentiment: 'positive',
    relatedPosts: [],
  },
  {
    topic: 'Tech Trends',
    hashtag: '#TechTrends2024',
    mentions: 756,
    growth: 35,
    sentiment: 'positive',
    relatedPosts: ['post-005'],
  },
  {
    topic: 'Remote Work',
    hashtag: '#RemoteWork',
    mentions: 623,
    growth: 15,
    sentiment: 'neutral',
    relatedPosts: ['post-006'],
  },
  {
    topic: 'AI Technology',
    hashtag: '#AITech',
    mentions: 589,
    growth: 78,
    sentiment: 'positive',
    relatedPosts: [],
  },
];

// Dashboard Summary
export const mockDashboardSummary = {
  totalFollowers: mockAccounts.reduce((sum, acc) => sum + acc.followersCount, 0),
  totalEngagement: mockPosts.reduce((sum, p) => sum + p.metrics.likes + p.metrics.comments + p.metrics.shares, 0),
  totalReach: mockPosts.reduce((sum, p) => sum + p.metrics.reach, 0),
  totalImpressions: mockPosts.reduce((sum, p) => sum + p.metrics.impressions, 0),
  avgEngagementRate: mockPosts.reduce((sum, p) => sum + p.metrics.engagementRate, 0) / mockPosts.length,
  totalPosts: mockPosts.length,
  avgSentiment: mockComments.reduce((sum, c) => sum + (c.sentimentScore || 0.5), 0) / mockComments.length,
  positiveSentimentPercent: (mockComments.filter(c => c.sentiment === 'positive').length / mockComments.length) * 100,
};
